# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: TrendMicro.Titanium-BBY
PackageVersion: 17.8.0.1121
InstallerType: exe
InstallerSwitches:
  Silent: --InstType=5 SILENT_EXTRACT
  SilentWithProgress: --InstType=5
Installers:
- InstallerUrl: https://files.trendmicro.com/products/Titanium/17.8/BBY/TTi_17.8_MR_Full.exe
  Architecture: x64
  InstallerSha256: C899E384E4BDA88D8343D4FF8A01E0BFF3A42A16707BD75CBC0098EB602E29C7
ManifestType: installer
ManifestVersion: 1.6.0
